name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install pytest-cov
      - name: Run tests
        run: |
          set -o pipefail
          pytest --cov=diabetes --cov-report=term-missing --cov-report=xml --cov-fail-under=85 | tee coverage.txt
          cat coverage.txt >> $GITHUB_STEP_SUMMARY
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage.xml
            coverage.txt
